---
# AUTHOR INFORMATION
title: jacobbas.github.io
name: Jacob Bas
description: Personal blog and website to house my thoughts
links:
  email:
    name: basjacob17@gmail.com
  github:
    name: JacobBas
  linkedin:
    name: jacob-bas-52019714b
  instagram:
    name: jacobthebas

# BUILD SETTINGS
collections:
  posts:
    permalink: "/news/:year/:month/:day/:title/"
    output: true
